export enum UserModalText {
  createUser = 'Хэрэглэгч үүсгэх',
  lastName = 'Хэрэглэгчийн овог:',
  firstName = 'Хэрэглэгчийн нэр: ',
  email = 'Цахим хаяг:',
  password = 'Нууц үг:',
  groupId = 'Хамаарагдах бүлгийн нэр:',
  role = 'Хэрэглэгчийн эрх:',
  cancel = 'Хаах',
  create = 'Үүсгэх',
  userNamePlaceHolder = 'Хэрэглэгчийн овгийг оруулна уу',
  userFirstNamePlaceHolder = 'Хэрэглэгчийн нэрийг оруулна уу',
  userEmailPlaceHolder = 'Хэрэглэгчийн цахим хаягийг оруулна уу',
  userPasswordPlaceHolder = 'Хэрэглэгчийн нууц үгийг оруулна уу',
}
