export enum GamificationModalText {
  createGamification = 'Урамшуулал үүсгэх',
  GamificationName = 'Урамшууллын нэр: ',
  group = 'Хамрагдах бүлэг',
  startDate = 'Эхлэх огноо',
  endDate = 'Дуусах огноо',
  assessmentNameInput = 'Үнэлгээний нэр',
  percentageOfAssessment = 'Урамшуулалд эзлэх хувь',
  assessmentDescription = '*Нэг урамшуулалд олон үнэлгээ сонгож болно.',
  awardNameInput = 'Цолны нэр',
  minAward = 'Босго хувь',
  maxAward = 'Дээд хувь',
  cancel = 'Хаах',
  create = 'Үүсгэх',
  GamificationNamePlaceHolder = 'Урамшууллын нэрийг оруулна уу',
  awardNamePlaceHolder = 'цолны нэрийг сонгоно уу',
  groupPlaceHolder = '',
  startDatePlaceHolder = 'mm/dd/yyyy',
  endDatePlaceHolder = 'mm/dd/yyyy',
}
